CREATE TABLE IF NOT EXISTS logs (
  id SERIAL PRIMARY KEY,
  value INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS values_table (
  id SERIAL PRIMARY KEY,
  value INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
